### ISSUE TITLE
Speed up yaml parsing for pipelines in searchpath

### ISSUE THREAD

**Issue by bryce-turner** [tgen/jetstream#143]
The more pipelines we have in the searchpath, the longer it takes to find the requested version of the pipeline. This is compounded by the length of the yaml as safe_loading will read/parse the entire yaml.

So far the expectation is that the pipeline.yaml starts with something similar to:
```yaml
__pipeline__:
  name: phoenix
  main: main.jst
  description: Human GRCh38 genomics suite
  version: development
```

Instead of reading the entire yaml before deciding that the pipeline doesn't match the version expected, we could read the header only.

This obviously has some caveats, first being that we would need to be strict about the organization of the pipeline.yaml. Additionally would need to decide on how many lines to read.

Solutions to these caveats are that we could fallback to parsing the entire yaml in the event that the quick read does not return a valid pipeline. As for number of lines, reading the first X lines should still match yaml specification (though there might be an issue if there are fewer lines than expected).
