### ISSUE TITLE
Task "description" directives should be ignored by identity

### ISSUE THREAD

**Issue by ryanrichholt** [tgen/jetstream#53]
There are currently several description directives used by phoenix: `tags`, `description`, `methods`

These should be ignored when calculating the identity of a task. One way to make this easy, lump them all under a single directive:

```yaml

- name: taskA
  input: file1.txt
  output: file2.txt
  description: String description should still be allowed
  cmd: |
      task command goes here

- name: taskB
  input: file2.txt
  output: file3.txt
  description:
    details: Now this could be arbitrary data
    methods: > But, all of it would be ignored by task identity
      because it's understood that nothing here will influence
      the behavior of the task, or its position in a workflow DAG
    tags: [file, info, processing] 
  cmd: |
      task command goes here
```
