### ISSUE TITLE
Task name namespacing

### ISSUE THREAD

**Issue by ryanrichholt** [tgen/jetstream#84]
Namespaces are a honking good idea. But tasks have no namespace. If two pipelines are run on the same project, and both pipelines have a task called `start`, it's tracking data will be overwritten by the last pipeline ran. This has been bugging me for a long time, but think I have an idea for how to fix it:

 Since the import system is handled entirely by Jinja, the template files would have to be pre-processed before loading and rendering. During this process, data could be added which the task loader can identify to prepend task names with pipeline/template info. 

> note in these examples I've excluded the template extensions in the syntax (see #83)

Example pipeline `foo`:

```yaml
# template_a

- name: foo
  cmd:  echo hello world

- name: bar
  cmd: echo the answer is 42

{% include 'foo/template_b' with context %}
```

```yaml 
# template_b

- name: baz
  cmd: echo What do you get if you multiply six by nine?

```

After preprocessing (still not sure if this would have to happen on disk when installing, or if the DictLoader in Jinja could be used)

```yaml
---
pipeline: foo
template: template_a
---
# template_a

- name: foo
  cmd:  echo hello world

- name: bar
  cmd: echo the answer is 42

{% include 'foo/template_b' with context %}
```

```yaml 
---
pipeline: foo
template: template_b
---
# template_b

- name: baz
  cmd: echo What do you get if you multiply six by nine?

```

Final document after rendering:

```yaml
---
pipeline: foo
template: template_a
---
# template_a

- name: foo
  cmd:  echo hello world

- name: bar
  cmd: echo the answer is 42

---
pipeline: foo
template: template_b
---
# template_b

- name: baz
  cmd: echo What do you get if you multiply six by nine?

```

And the loader would just:

```python
data = yaml.safe_load_all()

if data[0] != None:
    raise

# while get next two items
for td in tasks_data:
    td[name] = f'{pipeline/None}.{template}.{task_name/hash}
    task  = Task(**td)
```
